import { supabase } from "../lib/supabase";

export type RegulationsRow = {
  id: number;
  name: string | null;
  url: string | null;
};

/** شكل العلاقة المضمّنة في استعلامات أخرى (`regulations (...)`) */
export type RegulationsEmbedded = Pick<RegulationsRow, "id" | "name">;

/**
 * إدخال بدون `id` — العمود `GENERATED BY DEFAULT AS IDENTITY` في القاعدة.
 * يمكن تمرير `id` صراحةً عند الحاجة (مثل استيراد بيانات)، وفق إعدادات الهوية في PostgreSQL.
 */
export type CreateRegulationsInput = Partial<
  Pick<RegulationsRow, "id" | "name" | "url">
>;

export type UpdateRegulationsInput = Partial<
  Pick<RegulationsRow, "name" | "url">
>;

const tableName = "regulations" as const;

const selectRegulations = `
  id,
  name,
  url
`;

function parseNumericId(
  value: number | string,
  fieldLabel = "المعرّف",
): number {
  const n = typeof value === "string" ? Number(value) : value;
  if (typeof n !== "number" || !Number.isFinite(n)) {
    throw new Error(`${fieldLabel} غير صالح`);
  }
  return n;
}

export async function getAll(): Promise<RegulationsRow[]> {
  const { data, error } = await supabase
    .from(tableName)
    .select(selectRegulations)
    .order("id", { ascending: true });

  if (error) {
    console.error("Supabase error:", error);
    throw new Error("لا يمكن الحصول على بيانات اللوائح");
  }
  return (data as unknown as RegulationsRow[] | null) ?? [];
}

export async function getById(id: number | string): Promise<RegulationsRow> {
  const rowId = parseNumericId(id, "رقم اللائحة");

  const { data, error } = await supabase
    .from(tableName)
    .select(selectRegulations)
    .eq("id", rowId)
    .single();

  if (error) {
    console.error(error);
    throw new Error("لا يمكن الحصول على بيانات اللائحة");
  }
  return data as unknown as RegulationsRow;
}

export async function createRegulations(
  input: CreateRegulationsInput,
): Promise<RegulationsRow> {
  const { data, error } = await supabase
    .from(tableName)
    .insert({ ...input })
    .select(selectRegulations)
    .single();

  if (error) {
    console.error("Supabase error:", error);
    throw new Error(error.message || "لا يمكن تسجيل اللائحة");
  }
  return data as unknown as RegulationsRow;
}

export async function updateRegulations(
  id: number | string,
  patch: UpdateRegulationsInput,
): Promise<RegulationsRow> {
  const rowId = parseNumericId(id, "رقم اللائحة");

  const { data, error } = await supabase
    .from(tableName)
    .update({ ...patch })
    .eq("id", rowId)
    .select(selectRegulations)
    .single();

  if (error) {
    console.error(error);
    throw new Error("حدث خطأ عند تعديل اللائحة");
  }
  return data as unknown as RegulationsRow;
}

export async function deleteRegulations(id: number | string): Promise<unknown> {
  const rowId = parseNumericId(id, "رقم اللائحة");

  const { data, error } = await supabase
    .from(tableName)
    .delete()
    .eq("id", rowId);

  if (error) {
    console.error("Supabase error:", error);
    throw new Error("حدث خطأ عند حذف اللائحة");
  }
  return data;
}
