import { supabase } from "../lib/supabase";

export type WarehouseCategoriesClassificationsCategoryEmbed = {
  id: number;
  warehouse_category_name: string | null;
  status: boolean | null;
};

export type WarehouseCategoriesClassificationsRow = {
  id: number;
  classification_name: string | null;
  warehouse_category_id: number | null;
  notes: string | null;
  status: boolean | null;
};

export type WarehouseCategoriesClassificationsWithRelations =
  WarehouseCategoriesClassificationsRow & {
    warehouse_categories:
      | WarehouseCategoriesClassificationsCategoryEmbed
      | WarehouseCategoriesClassificationsCategoryEmbed[]
      | null;
  };

/**
 * إدخال بدون `id` — العمود `GENERATED BY DEFAULT AS IDENTITY` في القاعدة.
 * يمكن تمرير `id` صراحةً عند الحاجة (مثل استيراد بيانات)، وفق إعدادات الهوية في PostgreSQL.
 */
export type CreateWarehouseCategoriesClassificationsInput = Partial<
  Pick<
    WarehouseCategoriesClassificationsRow,
    | "id"
    | "classification_name"
    | "warehouse_category_id"
    | "notes"
    | "status"
  >
>;

export type UpdateWarehouseCategoriesClassificationsInput = Partial<
  Omit<WarehouseCategoriesClassificationsRow, "id">
>;

export type WarehouseCategoriesClassificationsListFilters = {
  warehouse_category_id?: number | string;
  activeOnly?: boolean;
};

const tableName = "warehouse_categories_classifications" as const;

const selectWarehouseCategoriesClassificationsEmbed = `
  id,
  classification_name,
  warehouse_category_id,
  notes,
  status,
  warehouse_categories ( id, warehouse_category_name, status )
`;

function parseNumericId(
  value: number | string,
  fieldLabel = "المعرّف",
): number {
  const n = typeof value === "string" ? Number(value) : value;
  if (typeof n !== "number" || !Number.isFinite(n)) {
    throw new Error(`${fieldLabel} غير صالح`);
  }
  return n;
}

export async function getAll(
  filters?: WarehouseCategoriesClassificationsListFilters,
): Promise<WarehouseCategoriesClassificationsWithRelations[]> {
  let query = supabase
    .from(tableName)
    .select(selectWarehouseCategoriesClassificationsEmbed)
    .order("warehouse_category_id", { ascending: true, nullsFirst: false })
    .order("id", { ascending: true });

  if (filters?.warehouse_category_id != null) {
    query = query.eq(
      "warehouse_category_id",
      parseNumericId(filters.warehouse_category_id, "تصنيف المستودع"),
    );
  }
  if (filters?.activeOnly === true) {
    query = query.eq("status", true);
  }

  const { data, error } = await query;

  if (error) {
    console.error("Supabase error:", error);
    throw new Error("لا يمكن الحصول على بيانات تصنيفات فرعية للمستودع");
  }
  return (
    (data as unknown as WarehouseCategoriesClassificationsWithRelations[] | null) ??
    []
  );
}

export async function getById(
  id: number | string,
): Promise<WarehouseCategoriesClassificationsWithRelations> {
  const rowId = parseNumericId(id, "رقم السجل");

  const { data, error } = await supabase
    .from(tableName)
    .select(selectWarehouseCategoriesClassificationsEmbed)
    .eq("id", rowId)
    .single();

  if (error) {
    console.error(error);
    throw new Error("لا يمكن الحصول على بيانات التصنيف الفرعي");
  }
  return data as unknown as WarehouseCategoriesClassificationsWithRelations;
}

export async function createWarehouseCategoriesClassifications(
  input: CreateWarehouseCategoriesClassificationsInput,
): Promise<WarehouseCategoriesClassificationsWithRelations> {
  const { data, error } = await supabase
    .from(tableName)
    .insert({ ...input })
    .select(selectWarehouseCategoriesClassificationsEmbed)
    .single();

  if (error) {
    console.error("Supabase error:", error);
    throw new Error(error.message || "لا يمكن تسجيل التصنيف الفرعي");
  }
  return data as unknown as WarehouseCategoriesClassificationsWithRelations;
}

export async function updateWarehouseCategoriesClassifications(
  id: number | string,
  patch: UpdateWarehouseCategoriesClassificationsInput,
): Promise<WarehouseCategoriesClassificationsWithRelations> {
  const rowId = parseNumericId(id, "رقم السجل");

  const { data, error } = await supabase
    .from(tableName)
    .update({ ...patch })
    .eq("id", rowId)
    .select(selectWarehouseCategoriesClassificationsEmbed)
    .single();

  if (error) {
    console.error(error);
    throw new Error("حدث خطأ عند تعديل التصنيف الفرعي");
  }
  return data as unknown as WarehouseCategoriesClassificationsWithRelations;
}

export async function deleteWarehouseCategoriesClassifications(
  id: number | string,
): Promise<unknown> {
  const rowId = parseNumericId(id, "رقم السجل");

  const { data, error } = await supabase
    .from(tableName)
    .delete()
    .eq("id", rowId);

  if (error) {
    console.error("Supabase error:", error);
    throw new Error("حدث خطأ عند حذف التصنيف الفرعي");
  }
  return data;
}
