import { supabase } from "../lib/supabase";

export type WarehouseCategoriesRow = {
  id: number;
  warehouse_category_name: string | null;
  notes: string | null;
  status: boolean | null;
};

/**
 * إدخال بدون `id` — العمود `GENERATED BY DEFAULT AS IDENTITY` في القاعدة.
 * يمكن تمرير `id` صراحةً عند الحاجة (مثل استيراد بيانات)، وفق إعدادات الهوية في PostgreSQL.
 */
export type CreateWarehouseCategoriesInput = Partial<
  Pick<
    WarehouseCategoriesRow,
    "id" | "warehouse_category_name" | "notes" | "status"
  >
>;

export type UpdateWarehouseCategoriesInput = Partial<
  Omit<WarehouseCategoriesRow, "id">
>;

export type WarehouseCategoriesListFilters = {
  activeOnly?: boolean;
};

const tableName = "warehouse_categories" as const;

const selectWarehouseCategories = `
  id,
  warehouse_category_name,
  notes,
  status
`;

function parseNumericId(
  value: number | string,
  fieldLabel = "المعرّف",
): number {
  const n = typeof value === "string" ? Number(value) : value;
  if (typeof n !== "number" || !Number.isFinite(n)) {
    throw new Error(`${fieldLabel} غير صالح`);
  }
  return n;
}

export async function getAll(
  filters?: WarehouseCategoriesListFilters,
): Promise<WarehouseCategoriesRow[]> {
  let query = supabase
    .from(tableName)
    .select(selectWarehouseCategories)
    .order("id", { ascending: true });

  if (filters?.activeOnly === true) {
    query = query.eq("status", true);
  }

  const { data, error } = await query;

  if (error) {
    console.error("Supabase error:", error);
    throw new Error("لا يمكن الحصول على بيانات تصنيفات المستودع");
  }
  return (data as unknown as WarehouseCategoriesRow[] | null) ?? [];
}

export async function getById(
  id: number | string,
): Promise<WarehouseCategoriesRow> {
  const rowId = parseNumericId(id, "رقم التصنيف");

  const { data, error } = await supabase
    .from(tableName)
    .select(selectWarehouseCategories)
    .eq("id", rowId)
    .single();

  if (error) {
    console.error(error);
    throw new Error("لا يمكن الحصول على بيانات تصنيف المستودع");
  }
  return data as unknown as WarehouseCategoriesRow;
}

export async function createWarehouseCategories(
  input: CreateWarehouseCategoriesInput,
): Promise<WarehouseCategoriesRow> {
  const { data, error } = await supabase
    .from(tableName)
    .insert({ ...input })
    .select(selectWarehouseCategories)
    .single();

  if (error) {
    console.error("Supabase error:", error);
    throw new Error(error.message || "لا يمكن تسجيل تصنيف المستودع");
  }
  return data as unknown as WarehouseCategoriesRow;
}

export async function updateWarehouseCategories(
  id: number | string,
  patch: UpdateWarehouseCategoriesInput,
): Promise<WarehouseCategoriesRow> {
  const rowId = parseNumericId(id, "رقم التصنيف");

  const { data, error } = await supabase
    .from(tableName)
    .update({ ...patch })
    .eq("id", rowId)
    .select(selectWarehouseCategories)
    .single();

  if (error) {
    console.error(error);
    throw new Error("حدث خطأ عند تعديل تصنيف المستودع");
  }
  return data as unknown as WarehouseCategoriesRow;
}

export async function deleteWarehouseCategories(
  id: number | string,
): Promise<unknown> {
  const rowId = parseNumericId(id, "رقم التصنيف");

  const { data, error } = await supabase
    .from(tableName)
    .delete()
    .eq("id", rowId);

  if (error) {
    console.error("Supabase error:", error);
    throw new Error("حدث خطأ عند حذف تصنيف المستودع");
  }
  return data;
}
